---
- name: Ensure `FABRIC_CA_HOME` directory
  become: true
  file:
    path: "{{ fabric_ca_home | mandatory }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Create fabric-ca-server-config.yaml
  template:
    src: "fabric-ca-server-config.yaml.jinja2"
    dest: "{{ fabric_ca_home | mandatory }}/fabric-ca-server-config.yaml"
  vars:
    operation_port: "{{ peer_operation_port | default(9443) }}"

- name: Remove mspconfig
  become: true
  file:
    path: "{{ fabric_ca_home | mandatory }}/{{ msp_config_name }}"
    state: absent

- name: Make sure ca msp dir exists
  file:
    path: "{{ fabric_ca_home | mandatory }}/{{ '/'.join(ca_private_key.split('/')[:-1]) }}"
    state: directory
    recurse: yes

- name: Make sure tlsca msp dir exists
  file:
    path: "{{ fabric_ca_home | mandatory }}/{{ '/'.join(ca_tls_key.split('/')[:-1]) }}"
    state: directory
    recurse: yes

- name: Copy mspconfig
  copy:
        src: "{{ playbook_dir }}/{{ item.path }}"
        dest: "{{ fabric_ca_home | mandatory }}/{{ item.path }}"
  with_items:
    - { path: "{{ ca_private_key }}" }
    - { path: "{{ ca_certificate }}" }
    - { path: "{{ ca_tls_key }}" }
    - { path: "{{ ca_tls_cert }}" }