- name: Remove old transaction files
  shell:
    cmd: rm *.tx -f
  args:
    chdir: "{{ caliper_workspace | mandatory }}/networks/"

- name: Copy channel creation transaction
  copy:
    src: "{{ playbook_dir }}/{{ bld_msp_config_name }}/mychannel.tx"
    dest: "{{ caliper_workspace | mandatory }}/networks/"

- name: Copy anchorpeer update transaction
  copy:
    src: "{{ playbook_dir }}/{{ bld_msp_config_name }}/{{ org.name | lower }}-anchor.tx"
    dest: "{{ caliper_workspace | mandatory }}/networks/"
  with_items:
    - "{{ bld_peer_orgs }}"
  loop_control:
    loop_var: org