- name: Remove mspconfig
  become: true
  file:
    path: "{{ fabric_cfg_path | mandatory }}/{{ bld_msp_config_name }}"
    state: absent

- name: Copy mspconfig
  copy:
        src: "{{ playbook_dir }}/{{ '/'.join(msp_dir.split('/')[:-1]) }}/{{ item.path }}"
        dest: "{{ fabric_cfg_path | mandatory }}/{{bld_msp_config_name}}/"
  with_items:
    - { path: "msp" }
    - { path: "tls" }