- name: Ensure `FABRIC_CFG_PATH` directory
  become: true
  file:
    path: "{{ fabric_cfg_path | mandatory }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755

- name: Create orderer.yaml
  template:
    src: orderer.yaml.jinja2
    dest: "{{ fabric_cfg_path | mandatory }}/orderer.yaml"
  vars:
    operation_port: "{{ orderer_operation_port | default(9443) }}"

- name: Remove mspconfig
  become: true
  file:
    path: "{{ fabric_cfg_path | mandatory }}/{{ msp_config_name }}"
    state: absent

- name: Copy mspconfig
  copy:
    src: "{{ playbook_dir }}/{{ '/'.join(msp_dir.split('/')[:-1]) }}/{{ item.path }}"
    dest: "{{ fabric_cfg_path | mandatory }}/{{ msp_config_name }}/"
  with_items:
    - { path: "msp" }
    - { path: "tls" }

- name: Setup genesis block
  copy:
    src: "{{ playbook_dir }}/{{ msp_config_name }}/genesis.block"
    dest: "{{ fabric_cfg_path }}/{{ msp_config_name }}/genesis.block"