- name: Ensure caliper workspace - newtorks
  become: true
  file:
    path: "{{ caliper_workspace | mandatory }}/networks"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0755
    recurse: true

- name: Create network config
  template:
    src: "network-config.yaml.jinja2"
    dest: "{{ caliper_workspace | mandatory }}/networks/fabric-go-tls.yaml"