- name: install chaincode
  block:
    - name: run setup-chaincode.sh
      command: bash -ic './setup-chaincode.sh'
      args:
        chdir: "{{ caliper_workspace | mandatory }}"
      register: ps
    - name: print result
      debug: 
        var: ps.stdout_lines
  when: role != "worker"