- name: go mod init
  shell:
    cmd: /bin/bash -ic 'go mod init {{ chaincode.name }}'
    chdir: "{{ caliper_workspace }}/src/{{ chaincode.name }}/golang"

- name: go mod tidy
  shell:
    cmd: /bin/bash -ic 'go mod tidy'
    chdir: "{{ caliper_workspace }}/src/{{ chaincode.name }}/golang"

- name: go mod vendor
  shell:
    cmd: /bin/bash -ic 'go mod vendor'
    chdir: "{{ caliper_workspace }}/src/{{ chaincode.name }}/golang"