- name: Install mosquitto 
  apt:
    name:
      - mosquitto
    state: present
    update_cache: yes

- name: Start mosquitto service
  become: true
  systemd:
    name: "mosquitto"
    enabled: yes
    state: started

